spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 113011
    url: jdbc:mariadb://localhost:3306/spring_project

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    properties:
      hibernate:
        #globally_quoted_identifiers: true
        format_sql: true

txtfilePath: classpath:/resources/